// Tests for src/game/enemies.{h,cc}.
// Spec: docs/test-plan/02-test-specifications.md §9 (T-ENM-005..060).
//
// HP-roll tests use seeds pinned in tests/seeds/expected_values.h: the
// concrete 38..41 / 51..53 outcomes depend on the host STL's
// uniform_int_distribution implementation, so values are not portable
// across toolchains — they are regenerated by tools/seed-pinner. The
// fixed kCombatTestSeed is used wherever a Combat is constructed, in
// line with the broader test suite convention.

#include <gtest/gtest.h>

#include <vector>

#include "sts2/game/combat.h"
#include "sts2/game/enemies.h"
#include "sts2/game/enemy.h"
#include "sts2/game/rng.h"
#include "sts2/game/types.h"
#include "sts2/game/vitals.h"
#include "tests/game/test_helpers.h"
#include "tests/seeds/expected_values.h"

namespace {

using sts2::tests::helpers::expect_powers_eq;
using sts2::tests::helpers::make_power;

using Combat = sts2::game::Combat;
using Enemy = sts2::game::Enemy;
using MoveId = sts2::game::MoveId;
using PowerKind = sts2::game::PowerKind;
using Rng = sts2::game::Rng;
using Stat = sts2::game::Stat;

using sts2::tests::seeds::kCalcifiedHpSeed42;
using sts2::tests::seeds::kCalcifiedSeedHp38;
using sts2::tests::seeds::kCalcifiedSeedHp39;
using sts2::tests::seeds::kCalcifiedSeedHp40;
using sts2::tests::seeds::kCalcifiedSeedHp41;
using sts2::tests::seeds::kCombatTestSeed;
using sts2::tests::seeds::kCultistTestSeed;
using sts2::tests::seeds::kDampHpSeed42;
using sts2::tests::seeds::kDampSeedHp51;
using sts2::tests::seeds::kDampSeedHp52;
using sts2::tests::seeds::kDampSeedHp53;

TEST(EnemiesCultistArchetypeCatalog, LooksUpByWireName) {
  const auto* calcified =
      sts2::enemies::cultist_archetype_from_wire_name("CalcifiedCultist");
  ASSERT_NE(calcified, nullptr);
  EXPECT_EQ(calcified->internal_name, "Calcified Cultist");
  EXPECT_EQ(calcified->wire_name, "CalcifiedCultist");
  EXPECT_EQ(calcified->hp_min, 38);
  EXPECT_EQ(calcified->hp_max, 41);
  EXPECT_EQ(calcified->dark_strike_base, 9);
  EXPECT_EQ(calcified->ritual_amount, 2);

  const auto* damp =
      sts2::enemies::cultist_archetype_from_wire_name("DampCultist");
  ASSERT_NE(damp, nullptr);
  EXPECT_EQ(damp->internal_name, "Damp Cultist");
  EXPECT_EQ(damp->wire_name, "DampCultist");
  EXPECT_EQ(damp->hp_min, 51);
  EXPECT_EQ(damp->hp_max, 53);
  EXPECT_EQ(damp->dark_strike_base, 1);
  EXPECT_EQ(damp->ritual_amount, 5);
}

TEST(EnemiesCultistArchetypeCatalog, LooksUpByInternalName) {
  const auto* calcified =
      sts2::enemies::cultist_archetype_from_internal_name("Calcified Cultist");
  ASSERT_NE(calcified, nullptr);
  EXPECT_EQ(calcified->wire_name, "CalcifiedCultist");

  const auto* damp =
      sts2::enemies::cultist_archetype_from_internal_name("Damp Cultist");
  ASSERT_NE(damp, nullptr);
  EXPECT_EQ(damp->wire_name, "DampCultist");
}

TEST(EnemiesCultistArchetypeCatalog, UnknownNameReturnsNull) {
  EXPECT_EQ(sts2::enemies::cultist_archetype_from_wire_name("JawWorm"),
            nullptr);
  EXPECT_EQ(sts2::enemies::cultist_archetype_from_internal_name("Jaw Worm"),
            nullptr);
}

// -------------------------------------------------------------------------
// 9.1  enemies::make_calcified_cultist(Rng&)
// -------------------------------------------------------------------------

// T-ENM-005 — BP, BV — Stable cultist with kCultistTestSeed. Pins all
// constructor invariants plus the def-use chain hp → max_hp/hp.
TEST(EnemiesMakeCalcified, T_ENM_005_StableCultistAtSeed42) {
  Rng r{kCultistTestSeed};
  Enemy e = sts2::enemies::make_calcified_cultist(r);

  EXPECT_EQ(e.name, "Calcified Cultist");
  EXPECT_EQ(e.vitals.max_hp, e.vitals.hp);
  EXPECT_EQ(e.vitals.hp, Stat{kCalcifiedHpSeed42});
  EXPECT_GE(e.vitals.hp, Stat{38});
  EXPECT_LE(e.vitals.hp, Stat{41});
  EXPECT_EQ(e.dark_strike_base, Stat{9});
  EXPECT_EQ(e.ritual_amount, Stat{2});
  EXPECT_EQ(e.current_move, MoveId::kIncantation);
  EXPECT_FALSE(e.performed_first_move);
  EXPECT_EQ(e.vitals.block, Stat{0});
  EXPECT_TRUE(e.vitals.powers.empty());
  EXPECT_EQ(e.kind, sts2::game::MonsterKind::kCultistCalcified);
}

// T-ENM-010 — EG, BV — All four HP outcomes 38..41 reachable; locks the
// closed-interval contract on uniform_int and that the constructor does
// not clamp.
TEST(EnemiesMakeCalcified, T_ENM_010_AllHpOutcomesReachable) {
  {
    Rng r{kCalcifiedSeedHp38};
    Enemy e = sts2::enemies::make_calcified_cultist(r);
    EXPECT_EQ(e.vitals.hp, Stat{38});
  }
  {
    Rng r{kCalcifiedSeedHp39};
    Enemy e = sts2::enemies::make_calcified_cultist(r);
    EXPECT_EQ(e.vitals.hp, Stat{39});
  }
  {
    Rng r{kCalcifiedSeedHp40};
    Enemy e = sts2::enemies::make_calcified_cultist(r);
    EXPECT_EQ(e.vitals.hp, Stat{40});
  }
  {
    Rng r{kCalcifiedSeedHp41};
    Enemy e = sts2::enemies::make_calcified_cultist(r);
    EXPECT_EQ(e.vitals.hp, Stat{41});
  }
}

// -------------------------------------------------------------------------
// 9.2  enemies::make_damp_cultist(Rng&)
// -------------------------------------------------------------------------

// T-ENM-015 — BP, BV — Mirror of T-ENM-005 for Damp.
TEST(EnemiesMakeDamp, T_ENM_015_StableCultistAtSeed42) {
  Rng r{kCultistTestSeed};
  Enemy e = sts2::enemies::make_damp_cultist(r);

  EXPECT_EQ(e.name, "Damp Cultist");
  EXPECT_EQ(e.vitals.max_hp, e.vitals.hp);
  EXPECT_EQ(e.vitals.hp, Stat{kDampHpSeed42});
  EXPECT_GE(e.vitals.hp, Stat{51});
  EXPECT_LE(e.vitals.hp, Stat{53});
  EXPECT_EQ(e.dark_strike_base, Stat{1});
  EXPECT_EQ(e.ritual_amount, Stat{5});
  EXPECT_EQ(e.current_move, MoveId::kIncantation);
  EXPECT_FALSE(e.performed_first_move);
  EXPECT_EQ(e.vitals.block, Stat{0});
  EXPECT_TRUE(e.vitals.powers.empty());
  EXPECT_EQ(e.kind, sts2::game::MonsterKind::kCultistDamp);
}

// T-ENM-020 — EG, BV — Three HP outcomes 51..53 reachable.
TEST(EnemiesMakeDamp, T_ENM_020_AllHpOutcomesReachable) {
  {
    Rng r{kDampSeedHp51};
    Enemy e = sts2::enemies::make_damp_cultist(r);
    EXPECT_EQ(e.vitals.hp, Stat{51});
  }
  {
    Rng r{kDampSeedHp52};
    Enemy e = sts2::enemies::make_damp_cultist(r);
    EXPECT_EQ(e.vitals.hp, Stat{52});
  }
  {
    Rng r{kDampSeedHp53};
    Enemy e = sts2::enemies::make_damp_cultist(r);
    EXPECT_EQ(e.vitals.hp, Stat{53});
  }
}

// -------------------------------------------------------------------------
// 9.3  enemies::roll_next_move(Enemy&)
// -------------------------------------------------------------------------

// T-ENM-025 — BP, EP — First call latches performed_first_move and leaves
// current_move untouched (D1 TRUE → P1).
TEST(EnemiesRollNextMove, T_ENM_025_FirstCallLatches) {
  Enemy e{};
  e.current_move = MoveId::kIncantation;
  e.performed_first_move = false;

  sts2::enemies::roll_next_move(e);

  EXPECT_TRUE(e.performed_first_move);
  EXPECT_EQ(e.current_move, MoveId::kIncantation);
}

// T-ENM-030 — BP, EP — Incantation → DarkStrike (D1 FALSE; D2 TRUE → P2).
TEST(EnemiesRollNextMove, T_ENM_030_IncantationToDarkStrike) {
  Enemy e{};
  e.current_move = MoveId::kIncantation;
  e.performed_first_move = true;

  sts2::enemies::roll_next_move(e);

  EXPECT_EQ(e.current_move, MoveId::kDarkStrike);
}

// T-ENM-035 — BP — DarkStrike stays (D1 FALSE; D2 FALSE → P3).
TEST(EnemiesRollNextMove, T_ENM_035_DarkStrikeStays) {
  Enemy e{};
  e.current_move = MoveId::kDarkStrike;
  e.performed_first_move = true;

  sts2::enemies::roll_next_move(e);

  EXPECT_EQ(e.current_move, MoveId::kDarkStrike);
}

// T-ENM-040 — DF — Sequence over 4 calls from a fresh enemy:
// [Incantation, DarkStrike, DarkStrike, DarkStrike]. Exercises P1 → P2 → P3 →
// P3.
TEST(EnemiesRollNextMove, T_ENM_040_SequenceOverFourCalls) {
  Enemy e{};
  // Defaults: current_move = Incantation, performed_first_move = false.
  ASSERT_EQ(e.current_move, MoveId::kIncantation);
  ASSERT_FALSE(e.performed_first_move);

  std::vector<MoveId> seq;
  for (int i = 0; i < 4; ++i) {
    sts2::enemies::roll_next_move(e);
    seq.push_back(e.current_move);
  }

  const std::vector<MoveId> expected = {
      MoveId::kIncantation,
      MoveId::kDarkStrike,
      MoveId::kDarkStrike,
      MoveId::kDarkStrike,
  };
  ASSERT_EQ(seq.size(), expected.size());
  for (std::size_t i = 0; i < expected.size(); ++i) {
    EXPECT_EQ(seq[i], expected[i]) << "mismatch at step " << i;
  }
}

// -------------------------------------------------------------------------
// 9.4  enemies::act(Enemy&, Combat&)
// -------------------------------------------------------------------------

// T-ENM-045 — BP, EP — Incantation case applies Ritual (amount = ritual_amount,
// just_applied = true) to the enemy itself via apply_power_to_enemy_self.
TEST(EnemiesAct, T_ENM_045_IncantationAppliesRitualToSelf) {
  Combat c{kCombatTestSeed};
  Enemy e{};
  e.ritual_amount = Stat{2};
  e.current_move = MoveId::kIncantation;

  sts2::enemies::act(e, c);

  expect_powers_eq(e.vitals.powers, {make_power(PowerKind::kRitual, 2, true)});
}

// T-ENM-050 — BP, EP — DarkStrike case attacks the player with raw base.
// Player default Vitals is {70, 70, 0, {}}; enemy has no powers.
TEST(EnemiesAct, T_ENM_050_DarkStrikeAttacksPlayer) {
  Combat c{kCombatTestSeed};
  Enemy e{};
  e.dark_strike_base = Stat{9};
  e.current_move = MoveId::kDarkStrike;

  sts2::enemies::act(e, c);

  EXPECT_EQ(c.player().vitals.hp, Stat{61});
}

// T-ENM-055 — DF — DarkStrike with Strength on enemy adds before block check;
// 9 base + 2 Strength = 11 raw damage. Locks integration with
// damage::compute_outgoing on the enemy-source path.
TEST(EnemiesAct, T_ENM_055_DarkStrikeWithStrengthAdds) {
  Combat c{kCombatTestSeed};
  Enemy e{};
  e.dark_strike_base = Stat{9};
  e.current_move = MoveId::kDarkStrike;
  e.vitals.powers = {make_power(PowerKind::kStrength, 2)};

  sts2::enemies::act(e, c);

  EXPECT_EQ(c.player().vitals.hp, Stat{70 - 11});  // 59
}

// T-ENM-060 — DF — DarkStrike with Weak on enemy applies 0.75 multiplier
// truncated to int: int(9 * 0.75) = int(6.75) = 6.
TEST(EnemiesAct, T_ENM_060_DarkStrikeWithWeakHalves) {
  Combat c{kCombatTestSeed};
  Enemy e{};
  e.dark_strike_base = Stat{9};
  e.current_move = MoveId::kDarkStrike;
  e.vitals.powers = {make_power(PowerKind::kWeak, 1)};

  sts2::enemies::act(e, c);

  EXPECT_EQ(c.player().vitals.hp, Stat{70 - 6});  // 64
}

// -------------------------------------------------------------------------
// LouseProgenitor factory
// -------------------------------------------------------------------------

// T-ENM-065 — BP — make_louse_progenitor at kCultistTestSeed yields a
// well-formed LP enemy: name, kind, HP within table range, spawn power
// CurlUp(14), initial move WebCannon.
TEST(EnemiesMakeLouseProgenitor, T_ENM_065_StableAtSeed42) {
  Rng r{kCultistTestSeed};
  Enemy e = sts2::enemies::make_louse_progenitor(r);
  EXPECT_EQ(e.name, "Louse Progenitor");
  EXPECT_EQ(e.kind, sts2::game::MonsterKind::kLouseProgenitor);
  EXPECT_GE(e.vitals.hp, Stat{134});
  EXPECT_LE(e.vitals.hp, Stat{136});
  EXPECT_EQ(e.vitals.hp, e.vitals.max_hp);
  EXPECT_EQ(e.current_move, MoveId::kWebCannon);
  EXPECT_FALSE(e.performed_first_move);
  EXPECT_EQ(e.vitals.block, Stat{0});
  ASSERT_EQ(e.vitals.powers.size(), 1U);
  EXPECT_EQ(e.vitals.powers[0].kind, sts2::game::PowerKind::kCurlUp);
  EXPECT_EQ(e.vitals.powers[0].amount, 14);
}

}  // namespace
