// Wave-21 pre-flight diagnostic: dumps cultist Zobrist key for post-wave-20
// main. Used ONCE to populate cultist_zobrist_pin.h with the byte-identity
// constants that wave-21.β's verification gate asserts against.
//
// Run via:
//   build/Release/sts2_oracle_tests
//     --gtest_filter='*DumpCultistZobristKey*'
//     --gtest_also_run_disabled_tests
//
// Output (paste into engine/cpp/tests/seeds/cultist_zobrist_pin.h):
//   inline constexpr uint64_t kCultistZobristKeyLo = 0xXXX;
//   inline constexpr uint64_t kCultistZobristKeyHi = 0xYYY;
//
// Kept DISABLED long-term so future Zobrist refactors can re-capture if
// needed (e.g., after seed re-roll per Q2-ADR-010 §Recovery).

#include <gtest/gtest.h>

#include <cstdint>
#include <iomanip>
#include <iostream>

#include "sts2/ai/state.h"
#include "sts2/ai/zobrist.h"
#include "sts2/game/combat.h"
#include "tests/game/test_helpers.h"
#include "tests/seeds/expected_values.h"

namespace {

TEST(WaveDiagnostic, DISABLED_DumpCultistZobristKey) {
  sts2::game::Combat combat = sts2::tests::helpers::make_starter_combat(
      sts2::tests::seeds::kCombatTestSeed);
  const sts2::ai::CompactState state = sts2::ai::from_combat(combat);
  const sts2::ai::ZobristKey key = sts2::ai::zobrist_of(state);

  std::cout << "// GENERATED by tests/seeds/dump_cultist_zobrist_key.cc\n";
  std::cout << "inline constexpr uint64_t kCultistZobristKeyLo = 0x" << std::hex
            << std::setw(16) << std::setfill('0') << key.lo << "ULL;\n";
  std::cout << "inline constexpr uint64_t kCultistZobristKeyHi = 0x" << std::hex
            << std::setw(16) << std::setfill('0') << key.hi << "ULL;\n";

  // Don't assert anything — this is a diagnostic dump.
  SUCCEED();
}

}  // namespace
