"""Render the AST analysis JSON into the Part 1 deliverable Markdown.

Run from repo root:
    .venv\\Scripts\\python.exe tools\\ast-analyzer\\generate_part1_doc.py    # Windows
    .venv/bin/python tools/ast-analyzer/generate_part1_doc.py                # Linux/macOS
"""

from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[2]
JSON_IN = REPO_ROOT / "tools" / "ast-analyzer" / "analysis.json"
DOC_OUT = REPO_ROOT / "docs" / "test-plan" / "01-ast-analysis.md"

# ---- Helpers ---------------------------------------------------------------

def fmt_decision(d: dict) -> str:
    expr = d.get("expr", "")
    if expr:
        # Tighten libclang's space-padded tokenization for readability.
        cleaned = expr.replace(" :: ", "::").replace(" .", ".").replace(". ", ".")
        cleaned = cleaned.replace(" ( ", "(").replace(" )", ")")
        cleaned = cleaned.replace(" ,", ",").replace(" ;", ";")
        cleaned = cleaned.replace(" [ ", "[").replace(" ]", "]")
        return f"`{cleaned}`"
    return "—"


def fmt_def_kind(k: str) -> str:
    return {
        "parameter":  "param",
        "init":       "init",
        "assign":     "=",
        "compound":   "+= etc.",
        "increment":  "++/--",
        "decl":       "decl",
        "local":      "local",
        "member":     "member",
        "unknown":    "?",
    }.get(k, k)


def file_link(path: str, line: int) -> str:
    return f"`{path}:{line}`"


# ---- Sections --------------------------------------------------------------

def render_header() -> list[str]:
    return [
        "# Part 1 — AST Analysis of sts2-ai",
        "",
        "**Source tree:** public headers in `include/sts2/`, implementations in `src/`. "
        "Analyzer covers all 21 translation units (every `.cc` under `src/`).  ",
        "**Standard:** C++20.  ",
        "**Tooling:** libclang via `tools/ast-analyzer/sts2_ast_analyzer.py`.  ",
        "**Generated by:** `tools/ast-analyzer/generate_part1_doc.py` from `analysis.json`.",
        "",
        "## Methodology",
        "",
        "1. Each `.cc` translation unit under `src/` is parsed with libclang "
        "(`-std=c++20 -Iinclude -Isrc`). Headers are pulled in transitively; "
        "definitions are deduplicated by `(file, name, line)`.",
        "2. **Types** — every `class`/`struct` definition reachable from a TU "
        "is enumerated with its fields, methods, and any virtual dispatch.",
        "3. **Functions** — every `FunctionDecl` / `CXXMethodDecl` / "
        "`FunctionTemplate` definition under `include/` or `src/` is recorded "
        "with its parent, parameters, return type, qualifiers, and body location.",
        "4. **Decision points** — `IfStmt`, all loop kinds (`WhileStmt`, "
        "`ForStmt`, `CXXForRangeStmt`, `DoStmt`), `ConditionalOperator`, "
        "`CaseStmt`/`DefaultStmt`, `CXXCatchStmt`, and short-circuit "
        "`&&`/`||` binary operators are counted. **Cyclomatic complexity** "
        "follows McCabe (CC = 1 + decisions, with each `case` adding 1, "
        "default adding 0). **Branches** are independent edges to be exercised "
        "for full branch coverage (binary decisions contribute 2; each `case` "
        "and `default` contribute 1; short-circuit operators contribute 2 — "
        "the short-cut path and the through-evaluation path).",
        "5. **Def-use pairs** — for every parameter, local, and field read inside "
        "a function body, libclang's referenced-cursor link tracks definition "
        "sites (parameter introduction, declaration with initializer, plain "
        "assignment, compound assignment, prefix/postfix increment) and use "
        "sites (any `DeclRefExpr`/`MemberRefExpr` resolving to that decl). "
        "Per-line dedup is applied so a use is counted once per line. The "
        "result is an intra-procedural def-use index — sufficient to drive "
        "all-defs and all-uses test selection without solving full reaching-"
        "definitions.",
        "",
        "## Limitations",
        "",
        "- Lambdas are reported as inner functions of their enclosing TU; the "
        "captures are visible to libclang but the per-lambda CC is not split "
        "out separately in this pass — they're folded into the enclosing "
        "function's body when the lambda body is walked. (See "
        "`cards::make_card` — the per-card lambda body is small and "
        "largely branch-free.)",
        "- Templates (only `Rng::shuffle` here) are analysed at their "
        "declaration. Type-dependent expressions parse as `UNEXPOSED_EXPR` but "
        "decisions are still counted correctly.",
        "- We do not resolve lambdas embedded in `std::function` initialisers "
        "for callers — they're tracked at the point of definition only.",
        "- Macro-only contributions (e.g. `assert`) are not modelled as "
        "branches, matching how compiled tests measure coverage with "
        "assertions enabled in Debug.",
        "",
    ]


def render_summary(types: dict, namespaces: dict, funcs: dict) -> list[str]:
    by_file = defaultdict(int)
    cc_buckets = {"trivial (CC=1)": 0, "simple (CC=2-3)": 0,
                  "moderate (CC=4-6)": 0, "complex (CC≥7)": 0}
    total_cc = 0
    total_branches = 0
    for fn in funcs.values():
        cc = fn["cyclomatic_complexity"]
        total_cc += cc
        total_branches += fn["branch_count"]
        by_file[fn["file"]] += 1
        if cc == 1:
            cc_buckets["trivial (CC=1)"] += 1
        elif cc <= 3:
            cc_buckets["simple (CC=2-3)"] += 1
        elif cc <= 6:
            cc_buckets["moderate (CC=4-6)"] += 1
        else:
            cc_buckets["complex (CC≥7)"] += 1

    lines = [
        "## Inventory at a glance",
        "",
        f"- **Classes** (have member functions): {sum(1 for t in types.values() if t['kind']=='class')}",
        f"- **Structs** (data aggregates): {sum(1 for t in types.values() if t['kind']=='struct')}",
        f"- **Namespaces hosting free functions**: {len(namespaces)}",
        f"- **Function definitions**: {len(funcs)}",
        f"- **Sum of cyclomatic complexity**: {total_cc}",
        f"- **Sum of branches to cover**: {total_branches}",
        "",
        "### Complexity distribution",
        "",
        "| Bucket | Count |",
        "|---|---:|",
    ]
    for k, v in cc_buckets.items():
        lines.append(f"| {k} | {v} |")
    lines.append("")
    lines.append("### Definitions per file")
    lines.append("")
    lines.append("| File | Functions defined |")
    lines.append("|---|---:|")
    for f, n in sorted(by_file.items()):
        lines.append(f"| `{f}` | {n} |")
    lines.append("")
    return lines


def render_types(types: dict, funcs: dict) -> list[str]:
    out = ["## Types", ""]
    classes = [t for t in types.values() if t["kind"] == "class"]
    structs = [t for t in types.values() if t["kind"] == "struct"]

    out.append("### Classes (with behaviour)")
    out.append("")
    for t in sorted(classes, key=lambda x: x["name"]):
        out.append(f"#### `{t['name']}` — {file_link(t['file'], t['line'])}")
        out.append("")
        if t["fields"]:
            out.append("**Members:**")
            out.append("")
            for f in t["fields"]:
                out.append(f"- `{f['type']} {f['name']};`")
            out.append("")
        if t["methods"]:
            out.append("**Methods:**")
            out.append("")
            out.append("| Method | Loc | CC | Branches | Decisions |")
            out.append("|---|---|---:|---:|---:|")
            for q in sorted(t["methods"]):
                fn = funcs.get(q, {})
                if not fn:
                    continue
                disp = fn["display_name"] or fn["spelling"]
                qualifiers = []
                if fn.get("is_const"):
                    qualifiers.append("const")
                if fn.get("is_static"):
                    qualifiers.append("static")
                if fn.get("is_template"):
                    qualifiers.append("template")
                qstr = " " + " ".join(f"_{q}_" for q in qualifiers) if qualifiers else ""
                out.append(f"| `{disp}`{qstr} | "
                           f"{file_link(fn['file'], fn['line'])} | "
                           f"{fn['cyclomatic_complexity']} | "
                           f"{fn['branch_count']} | "
                           f"{len(fn['decisions'])} |")
            out.append("")
        if t.get("is_polymorphic"):
            out.append("> ⚠ Polymorphic (has virtual functions). Tests must "
                      "exercise dynamic dispatch.")
            out.append("")

    out.append("### Structs (data aggregates)")
    out.append("")
    for t in sorted(structs, key=lambda x: x["name"]):
        out.append(f"#### `{t['name']}` — {file_link(t['file'], t['line'])}")
        out.append("")
        if t["fields"]:
            for f in t["fields"]:
                out.append(f"- `{f['type']} {f['name']};`")
            out.append("")
        else:
            out.append("_(no public fields enumerated by the analyzer — likely "
                       "an enum-tagged record or one whose members are "
                       "in-class initialised below visibility default)_")
            out.append("")
    return out


def render_namespaces(namespaces: dict, funcs: dict) -> list[str]:
    out = ["## Namespaces (free-function modules)", ""]
    for nsname in sorted(namespaces.keys()):
        ns = namespaces[nsname]
        out.append(f"### `namespace {nsname}` — files: "
                   + ", ".join(f"`{f}`" for f in ns["files"]))
        out.append("")
        out.append("| Function | Loc | CC | Branches | Decisions |")
        out.append("|---|---|---:|---:|---:|")
        for q in sorted(ns["free_functions"]):
            fn = funcs.get(q, {})
            if not fn:
                continue
            disp = fn["display_name"] or fn["spelling"]
            out.append(f"| `{disp}` | "
                       f"{file_link(fn['file'], fn['line'])} | "
                       f"{fn['cyclomatic_complexity']} | "
                       f"{fn['branch_count']} | "
                       f"{len(fn['decisions'])} |")
        out.append("")
    return out


def render_unattached_funcs(funcs: dict) -> list[str]:
    """Free functions in anonymous namespaces or main()."""
    out = ["## Translation-unit-local helpers and `main`", ""]
    rows = []
    for q, fn in funcs.items():
        if fn["is_method"]:
            continue
        if fn["parent_kind"] == "namespace" and fn["parent_name"]:
            continue
        rows.append(fn)
    rows.sort(key=lambda f: (f["file"], f["line"]))
    if not rows:
        return out
    out.append("These are TU-local (`namespace { }` or `static`) and "
               "`main()`. They are testable only via end-to-end execution or "
               "by extracting/exposing them.")
    out.append("")
    out.append("| Function | Loc | CC | Branches |")
    out.append("|---|---|---:|---:|")
    for fn in rows:
        out.append(f"| `{fn['display_name']}` | "
                   f"{file_link(fn['file'], fn['line'])} | "
                   f"{fn['cyclomatic_complexity']} | "
                   f"{fn['branch_count']} |")
    out.append("")
    return out


def render_function_detail(funcs: dict) -> list[str]:
    """Per-function CFG and def-use detail. Sorted by file then line."""
    out = ["## Per-function control flow and def-use", ""]
    out.append("Functions with **CC = 1** and no parameters are listed in the "
               "tables above without expansion here.")
    out.append("")

    rows = sorted(funcs.values(), key=lambda f: (f["file"], f["line"]))
    for fn in rows:
        if fn["cyclomatic_complexity"] == 1 and not fn["def_use"]:
            continue

        title = fn["qualified"]
        if fn["display_name"]:
            sig = fn["display_name"]
        else:
            sig = fn["spelling"]
        out.append(f"### `{title}`")
        out.append("")
        out.append(f"- **Signature:** `{fn['return_type']} {sig}` "
                   + ("`const`" if fn.get("is_const") else "")
                   + ("`static`" if fn.get("is_static") else "")
                   + ("`template`" if fn.get("is_template") else ""))
        out.append(f"- **Location:** {file_link(fn['file'], fn['line'])}–"
                   f"`{fn['end_line']}`")
        out.append(f"- **Cyclomatic complexity:** {fn['cyclomatic_complexity']}  "
                   f"**Branches to cover:** {fn['branch_count']}  "
                   f"**Statements (proxy):** {fn['statements']}")
        out.append("")

        # Decisions
        if fn["decisions"]:
            out.append("**Decision points:**")
            out.append("")
            out.append("| # | Kind | Line | Condition |")
            out.append("|---:|---|---:|---|")
            for i, d in enumerate(fn["decisions"], 1):
                out.append(f"| {i} | `{d['kind']}` | {d['line']} | "
                           f"{fmt_decision(d)} |")
            out.append("")

        # Def-use
        if fn["def_use"]:
            out.append("**Def-use pairs (variables referenced in body):**")
            out.append("")
            out.append("| Variable | Storage | Decl line | Defs | Uses |")
            out.append("|---|---|---:|---|---|")
            for name, du in sorted(fn["def_use"].items()):
                if name.startswith("<") or name == "":
                    continue
                defs = ", ".join(f"L{d['line']}({fmt_def_kind(d['kind'])})"
                                 for d in du["defs"])
                uses = ", ".join(f"L{l}" for l in du["uses"])
                out.append(f"| `{name}` | {du['decl_kind']} | "
                           f"{du['decl_line'] or '—'} | {defs or '—'} | "
                           f"{uses or '—'} |")
            out.append("")
    return out


def render_hot_spots(funcs: dict) -> list[str]:
    """Functions where SDET attention concentrates: high CC, many branches,
    many def-use sites. These are the prime targets for structured-basis and
    data-flow tests in Part 2."""
    rows = sorted(funcs.values(),
                  key=lambda f: (-f["cyclomatic_complexity"],
                                 -f["branch_count"],
                                 -len(f.get("def_use", {}))))
    out = ["## Hot spots for SDET attention", ""]
    out.append("Ranked by cyclomatic complexity. The top entries are where "
               "structured-basis testing must concentrate independent paths "
               "and where def-use coverage drives the most all-uses pairs.")
    out.append("")
    out.append("| # | Function | Loc | CC | Branches | Stmts | Def-use vars |")
    out.append("|---:|---|---|---:|---:|---:|---:|")
    for i, fn in enumerate(rows[:15], 1):
        defuse_n = sum(1 for k in fn.get("def_use", {}) if not k.startswith("<") and k)
        out.append(f"| {i} | `{fn['qualified']}` | "
                   f"{file_link(fn['file'], fn['line'])} | "
                   f"{fn['cyclomatic_complexity']} | "
                   f"{fn['branch_count']} | "
                   f"{fn['statements']} | "
                   f"{defuse_n} |")
    out.append("")
    return out


def render_coverage_targets(funcs: dict) -> list[str]:
    """Per-module CC/branch/statement breakdown so coverage targets land per
    module rather than only globally."""
    by_module: dict[str, dict] = defaultdict(
        lambda: {"funcs": 0, "cc": 0, "branches": 0, "stmts": 0})
    for fn in funcs.values():
        path = fn["file"]
        # module = first path segment after src/ or include/sts2/
        parts = path.split("/")
        if parts[0] == "include" and len(parts) >= 3:
            mod = parts[2]
        elif parts[0] == "src" and len(parts) >= 2:
            mod = parts[1] if parts[1] != "main.cc" else "_root"
        else:
            mod = parts[0]
        m = by_module[mod]
        m["funcs"] += 1
        m["cc"] += fn["cyclomatic_complexity"]
        m["branches"] += fn["branch_count"]
        m["stmts"] += fn["statements"]
    out = ["## Coverage-target derivation per module", ""]
    out.append("100% branch coverage means **every branch in the right column "
               "must be exercised** by at least one test in Part 2. The "
               "≥70% statement floor means **at most 30% of `Stmts` may go "
               "uncovered** in any module — the analyzer's statement count is "
               "a proxy (DECL/RETURN/IF/SWITCH/loop/break/continue/try/throw) "
               "and is conservative compared to gcov line counts, so the floor "
               "remains binding.")
    out.append("")
    out.append("| Module | Funcs | CC sum | Branches to cover | Stmt proxy | Stmt budget @70% |")
    out.append("|---|---:|---:|---:|---:|---:|")
    total = {"funcs": 0, "cc": 0, "branches": 0, "stmts": 0}
    for mod in sorted(by_module):
        m = by_module[mod]
        budget = max(0, int(round(m["stmts"] * 0.70)))
        out.append(f"| `{mod}` | {m['funcs']} | {m['cc']} | "
                   f"{m['branches']} | {m['stmts']} | {budget} |")
        for k in total:
            total[k] += m[k]
    budget = max(0, int(round(total["stmts"] * 0.70)))
    out.append(f"| **total** | **{total['funcs']}** | **{total['cc']}** | "
               f"**{total['branches']}** | **{total['stmts']}** | **{budget}** |")
    out.append("")
    return out


def render_testability_notes() -> list[str]:
    return [
        "## Testability notes",
        "",
        "- **`Combat` — non-deterministic external state.** It owns an `Rng` "
        "by value (`rng_`) seeded in the constructor. Tests targeting "
        "`Combat::start`, `Combat::start_player_turn`, `Combat::end_turn` "
        "must seed deterministically and read pile state through the public "
        "accessors.",
        "- **`Rng::shuffle` is a function template.** Coverage for the "
        "non-trivial path requires instantiating it with at least one "
        "concrete `T` (`Card` is the canonical caller).",
        "- **Lambda in `cards::make_card`.** `Card::on_play` is a small "
        "closure that calls `Combat` mutators based on `CardEffect` flags. "
        "Branch coverage is reached by playing each card in a `Combat` "
        "fixture; the closure has CC=1 but the data-flow goes through "
        "`Combat`.",
        "- **TU-local helpers** in anonymous namespaces (e.g. "
        "`render.cc::format_powers`, `input.cc::trim`) are not directly "
        "linkable from outside their TU. They are exposed for tests via "
        "`*_internal.h` headers under `src/<module>/` "
        "(`render_internal.h`, `input_internal.h`). "
        "Public entry points (`sts2::render::render_combat`, "
        "`sts2::input::read_action`, etc.) cover them indirectly.",
        "- **`main()` and `parse_args`** are testable only via process-level "
        "tests (spawn `sts2_fight` with argv). They drive end-to-end "
        "coverage of `Combat::start` and the prompt loop.",
        "- **No exceptions** are thrown by the implementation. `assert` "
        "(in `combat.cc`) fires only on internal contract violations and "
        "is not part of user-visible behaviour to test.",
        "- **AI layer (`sts2::ai`)** operates on a `CompactState` snapshot "
        "rather than `Combat`. `from_combat` is the marshaller and "
        "`apply_player_action`/`apply_draw`/`enemy_act` are pure-ish "
        "transitions. Tests can construct `CompactState` directly without "
        "running a full `Combat`, which keeps AI tests fast and fully "
        "deterministic.",
        "- **`Search::solve_player`/`solve_chance`** memoize via "
        "`unordered_map<CompactState, ...>` keyed by `CompactStateHash`. "
        "Cache hits/misses are not user-visible, but tests must clear or "
        "reseed the search instance between scenarios to avoid cross-test "
        "memoization leakage.",
        "- **Renderer (`sts2::render`)** writes to a caller-supplied "
        "`std::ostream`. Tests should capture into `std::ostringstream` and "
        "match against ANSI/UTF-8 substrings; the `render_internal.h` "
        "header exposes formatters such as `format_powers` and `hp_bar` for "
        "narrower unit tests.",
        "- **Input (`sts2::input`)** is line-buffered and stream-driven. "
        "`detail::trim` and the dispatcher are exposed via "
        "`input_internal.h`. EOF and malformed lines should be exercised "
        "explicitly (see `read_action`, CC=8).",
        "- **Recommender / PV reconstruction** (`Recommender::recommend`, "
        "`render_ai_recommendation`) blends search results with rendering. "
        "Set both `tt_size` and a deterministic `Search` seed for stable "
        "tests, and capture the rendered PV alongside the chosen action.",
        "- **`HandIndex` / `EnemySlot` are strong int wrappers.** They "
        "introduce `in_range` / `at` checks. Boundary tests "
        "(`-1`, `0`, `size-1`, `size`) on these primitives propagate to "
        "every method that takes them as parameters — equivalence "
        "partitioning at this seam is high leverage.",
        "",
    ]


def main() -> int:
    data = json.loads(JSON_IN.read_text(encoding="utf-8"))
    types = data["types"]
    namespaces = data["namespaces"]
    funcs = data["functions"]

    parts: list[str] = []
    parts += render_header()
    parts += render_summary(types, namespaces, funcs)
    parts += render_hot_spots(funcs)
    parts += render_coverage_targets(funcs)
    parts += render_types(types, funcs)
    parts += render_namespaces(namespaces, funcs)
    parts += render_unattached_funcs(funcs)
    parts += render_function_detail(funcs)
    parts += render_testability_notes()

    DOC_OUT.parent.mkdir(parents=True, exist_ok=True)
    DOC_OUT.write_text("\n".join(parts) + "\n", encoding="utf-8")
    print(f"Wrote {DOC_OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
