"""Render the AST analysis JSON into the Part 1 deliverable Markdown.

Run:
    .venv\\Scripts\\python.exe tools\\ast-analyzer\\generate_part1_doc.py
"""

from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[2]
JSON_IN = REPO_ROOT / "tools" / "ast-analyzer" / "analysis.json"
DOC_OUT = REPO_ROOT / "docs" / "test-plan" / "01-ast-analysis.md"

# ---- Helpers ---------------------------------------------------------------

def fmt_decision(d: dict) -> str:
    expr = d.get("expr", "")
    if expr:
        # Tighten libclang's space-padded tokenization for readability.
        cleaned = expr.replace(" :: ", "::").replace(" .", ".").replace(". ", ".")
        cleaned = cleaned.replace(" ( ", "(").replace(" )", ")")
        cleaned = cleaned.replace(" ,", ",").replace(" ;", ";")
        cleaned = cleaned.replace(" [ ", "[").replace(" ]", "]")
        return f"`{cleaned}`"
    return "—"


def fmt_def_kind(k: str) -> str:
    return {
        "parameter":  "param",
        "init":       "init",
        "assign":     "=",
        "compound":   "+= etc.",
        "increment":  "++/--",
        "decl":       "decl",
        "local":      "local",
        "member":     "member",
        "unknown":    "?",
    }.get(k, k)


def file_link(path: str, line: int) -> str:
    return f"`{path}:{line}`"


# ---- Sections --------------------------------------------------------------

def render_header() -> list[str]:
    return [
        "# Part 1 — AST Analysis of sts2-ai",
        "",
        "**Source tree:** `src/` — 18 headers, 11 translation units, 1 107 LOC.  ",
        "**Standard:** C++20.  ",
        "**Tooling:** libclang 18.1.1 via `tools/ast-analyzer/sts2_ast_analyzer.py`.  ",
        "**Generated by:** `tools/ast-analyzer/generate_part1_doc.py` from `analysis.json`.",
        "",
        "## Methodology",
        "",
        "1. Each `.cpp` translation unit under `src/` is parsed with libclang "
        "(`-std=c++20 -Isrc`). Headers are pulled in transitively; "
        "definitions are deduplicated by `(file, name, line)`.",
        "2. **Types** — every `class`/`struct` definition reachable from a TU "
        "is enumerated with its fields, methods, and any virtual dispatch.",
        "3. **Functions** — every `FunctionDecl` / `CXXMethodDecl` / "
        "`FunctionTemplate` definition in `src/` is recorded with its parent, "
        "parameters, return type, qualifiers, and body location.",
        "4. **Decision points** — `IfStmt`, all loop kinds (`WhileStmt`, "
        "`ForStmt`, `CXXForRangeStmt`, `DoStmt`), `ConditionalOperator`, "
        "`CaseStmt`/`DefaultStmt`, `CXXCatchStmt`, and short-circuit "
        "`&&`/`||` binary operators are counted. **Cyclomatic complexity** "
        "follows McCabe (CC = 1 + decisions, with each `case` adding 1, "
        "default adding 0). **Branches** are independent edges to be exercised "
        "for full branch coverage (binary decisions contribute 2; each `case` "
        "and `default` contribute 1; short-circuit operators contribute 2 — "
        "the short-cut path and the through-evaluation path).",
        "5. **Def-use pairs** — for every parameter, local, and field read inside "
        "a function body, libclang's referenced-cursor link tracks definition "
        "sites (parameter introduction, declaration with initializer, plain "
        "assignment, compound assignment, prefix/postfix increment) and use "
        "sites (any `DeclRefExpr`/`MemberRefExpr` resolving to that decl). "
        "Per-line dedup is applied so a use is counted once per line. The "
        "result is an intra-procedural def-use index — sufficient to drive "
        "all-defs and all-uses test selection without solving full reaching-"
        "definitions.",
        "",
        "## Limitations",
        "",
        "- Lambdas are reported as inner functions of their enclosing TU; the "
        "captures are visible to libclang but the per-lambda CC is not split "
        "out separately in this pass — they're folded into the enclosing "
        "function's body when the lambda body is walked. (See "
        "`cards::make_strike` etc. — the lambda's body is small and "
        "branch-free.)",
        "- Templates (only `Rng::shuffle` here) are analysed at their "
        "declaration. Type-dependent expressions parse as `UNEXPOSED_EXPR` but "
        "decisions are still counted correctly.",
        "- We do not resolve lambdas embedded in `std::function` initialisers "
        "for callers — they're tracked at the point of definition only.",
        "- Macro-only contributions (e.g. `assert`) are not modelled as "
        "branches, matching how compiled tests measure coverage with "
        "assertions enabled in Debug.",
        "",
    ]


def render_summary(types: dict, namespaces: dict, funcs: dict) -> list[str]:
    by_file = defaultdict(int)
    cc_buckets = {"trivial (CC=1)": 0, "simple (CC=2-3)": 0,
                  "moderate (CC=4-6)": 0, "complex (CC≥7)": 0}
    total_cc = 0
    total_branches = 0
    for fn in funcs.values():
        cc = fn["cyclomatic_complexity"]
        total_cc += cc
        total_branches += fn["branch_count"]
        by_file[fn["file"]] += 1
        if cc == 1:
            cc_buckets["trivial (CC=1)"] += 1
        elif cc <= 3:
            cc_buckets["simple (CC=2-3)"] += 1
        elif cc <= 6:
            cc_buckets["moderate (CC=4-6)"] += 1
        else:
            cc_buckets["complex (CC≥7)"] += 1

    lines = [
        "## Inventory at a glance",
        "",
        f"- **Classes** (have member functions): {sum(1 for t in types.values() if t['kind']=='class')}",
        f"- **Structs** (data aggregates): {sum(1 for t in types.values() if t['kind']=='struct')}",
        f"- **Namespaces hosting free functions**: {len(namespaces)}",
        f"- **Function definitions**: {len(funcs)}",
        f"- **Sum of cyclomatic complexity**: {total_cc}",
        f"- **Sum of branches to cover**: {total_branches}",
        "",
        "### Complexity distribution",
        "",
        "| Bucket | Count |",
        "|---|---:|",
    ]
    for k, v in cc_buckets.items():
        lines.append(f"| {k} | {v} |")
    lines.append("")
    lines.append("### Definitions per file")
    lines.append("")
    lines.append("| File | Functions defined |")
    lines.append("|---|---:|")
    for f, n in sorted(by_file.items()):
        lines.append(f"| `{f}` | {n} |")
    lines.append("")
    return lines


def render_types(types: dict, funcs: dict) -> list[str]:
    out = ["## Types", ""]
    classes = [t for t in types.values() if t["kind"] == "class"]
    structs = [t for t in types.values() if t["kind"] == "struct"]

    out.append("### Classes (with behaviour)")
    out.append("")
    for t in sorted(classes, key=lambda x: x["name"]):
        out.append(f"#### `{t['name']}` — {file_link(t['file'], t['line'])}")
        out.append("")
        if t["fields"]:
            out.append("**Members:**")
            out.append("")
            for f in t["fields"]:
                out.append(f"- `{f['type']} {f['name']};`")
            out.append("")
        if t["methods"]:
            out.append("**Methods:**")
            out.append("")
            out.append("| Method | Loc | CC | Branches | Decisions |")
            out.append("|---|---|---:|---:|---:|")
            for q in sorted(t["methods"]):
                fn = funcs.get(q, {})
                if not fn:
                    continue
                disp = fn["display_name"] or fn["spelling"]
                qualifiers = []
                if fn.get("is_const"):
                    qualifiers.append("const")
                if fn.get("is_static"):
                    qualifiers.append("static")
                if fn.get("is_template"):
                    qualifiers.append("template")
                qstr = " " + " ".join(f"_{q}_" for q in qualifiers) if qualifiers else ""
                out.append(f"| `{disp}`{qstr} | "
                           f"{file_link(fn['file'], fn['line'])} | "
                           f"{fn['cyclomatic_complexity']} | "
                           f"{fn['branch_count']} | "
                           f"{len(fn['decisions'])} |")
            out.append("")
        if t.get("is_polymorphic"):
            out.append("> ⚠ Polymorphic (has virtual functions). Tests must "
                      "exercise dynamic dispatch.")
            out.append("")

    out.append("### Structs (data aggregates)")
    out.append("")
    for t in sorted(structs, key=lambda x: x["name"]):
        out.append(f"#### `{t['name']}` — {file_link(t['file'], t['line'])}")
        out.append("")
        if t["fields"]:
            for f in t["fields"]:
                out.append(f"- `{f['type']} {f['name']};`")
            out.append("")
        else:
            out.append("_(no public fields enumerated by the analyzer — likely "
                       "an enum-tagged record or one whose members are "
                       "in-class initialised below visibility default)_")
            out.append("")
    return out


def render_namespaces(namespaces: dict, funcs: dict) -> list[str]:
    out = ["## Namespaces (free-function modules)", ""]
    for nsname in sorted(namespaces.keys()):
        ns = namespaces[nsname]
        out.append(f"### `namespace {nsname}` — files: "
                   + ", ".join(f"`{f}`" for f in ns["files"]))
        out.append("")
        out.append("| Function | Loc | CC | Branches | Decisions |")
        out.append("|---|---|---:|---:|---:|")
        for q in sorted(ns["free_functions"]):
            fn = funcs.get(q, {})
            if not fn:
                continue
            disp = fn["display_name"] or fn["spelling"]
            out.append(f"| `{disp}` | "
                       f"{file_link(fn['file'], fn['line'])} | "
                       f"{fn['cyclomatic_complexity']} | "
                       f"{fn['branch_count']} | "
                       f"{len(fn['decisions'])} |")
        out.append("")
    return out


def render_unattached_funcs(funcs: dict) -> list[str]:
    """Free functions in anonymous namespaces or main()."""
    out = ["## Translation-unit-local helpers and `main`", ""]
    rows = []
    for q, fn in funcs.items():
        if fn["is_method"]:
            continue
        if fn["parent_kind"] == "namespace" and fn["parent_name"]:
            continue
        rows.append(fn)
    rows.sort(key=lambda f: (f["file"], f["line"]))
    if not rows:
        return out
    out.append("These are TU-local (`namespace { }` or `static`) and "
               "`main()`. They are testable only via end-to-end execution or "
               "by extracting/exposing them.")
    out.append("")
    out.append("| Function | Loc | CC | Branches |")
    out.append("|---|---|---:|---:|")
    for fn in rows:
        out.append(f"| `{fn['display_name']}` | "
                   f"{file_link(fn['file'], fn['line'])} | "
                   f"{fn['cyclomatic_complexity']} | "
                   f"{fn['branch_count']} |")
    out.append("")
    return out


def render_function_detail(funcs: dict) -> list[str]:
    """Per-function CFG and def-use detail. Sorted by file then line."""
    out = ["## Per-function control flow and def-use", ""]
    out.append("Functions with **CC = 1** and no parameters are listed in the "
               "tables above without expansion here.")
    out.append("")

    rows = sorted(funcs.values(), key=lambda f: (f["file"], f["line"]))
    for fn in rows:
        if fn["cyclomatic_complexity"] == 1 and not fn["def_use"]:
            continue

        title = fn["qualified"]
        if fn["display_name"]:
            sig = fn["display_name"]
        else:
            sig = fn["spelling"]
        out.append(f"### `{title}`")
        out.append("")
        out.append(f"- **Signature:** `{fn['return_type']} {sig}` "
                   + ("`const`" if fn.get("is_const") else "")
                   + ("`static`" if fn.get("is_static") else "")
                   + ("`template`" if fn.get("is_template") else ""))
        out.append(f"- **Location:** {file_link(fn['file'], fn['line'])}–"
                   f"`{fn['end_line']}`")
        out.append(f"- **Cyclomatic complexity:** {fn['cyclomatic_complexity']}  "
                   f"**Branches to cover:** {fn['branch_count']}  "
                   f"**Statements (proxy):** {fn['statements']}")
        out.append("")

        # Decisions
        if fn["decisions"]:
            out.append("**Decision points:**")
            out.append("")
            out.append("| # | Kind | Line | Condition |")
            out.append("|---:|---|---:|---|")
            for i, d in enumerate(fn["decisions"], 1):
                out.append(f"| {i} | `{d['kind']}` | {d['line']} | "
                           f"{fmt_decision(d)} |")
            out.append("")

        # Def-use
        if fn["def_use"]:
            out.append("**Def-use pairs (variables referenced in body):**")
            out.append("")
            out.append("| Variable | Storage | Decl line | Defs | Uses |")
            out.append("|---|---|---:|---|---|")
            for name, du in sorted(fn["def_use"].items()):
                if name.startswith("<") or name == "":
                    continue
                defs = ", ".join(f"L{d['line']}({fmt_def_kind(d['kind'])})"
                                 for d in du["defs"])
                uses = ", ".join(f"L{l}" for l in du["uses"])
                out.append(f"| `{name}` | {du['decl_kind']} | "
                           f"{du['decl_line'] or '—'} | {defs or '—'} | "
                           f"{uses or '—'} |")
            out.append("")
    return out


def render_testability_notes() -> list[str]:
    return [
        "## Testability notes",
        "",
        "- **`Combat` — non-deterministic external state.** It owns an `Rng` "
        "by value (`rng_`) seeded in the constructor. Tests targeting "
        "`Combat::draw`, `Combat::reshuffle`, `Combat::start` must seed "
        "deterministically and read pile state through the public accessors.",
        "- **`Rng::shuffle` is a function template.** Coverage for the "
        "non-trivial path requires instantiating it with at least one "
        "concrete `T` (`Card` is the canonical caller).",
        "- **Lambdas in `cards::make_*`.** Each `Card::on_play` is a small "
        "closure that calls `Combat` mutators. Branch coverage of those "
        "closures is reached by playing the corresponding card in a `Combat` "
        "fixture; they have CC=1 but the data-flow goes through `Combat`.",
        "- **Friend `CombatTestAccess`** is forward-declared at "
        "`src/game/Combat.h:56`. The test suite was removed (commit "
        "`179523f`); the friend hook remains and is the intended white-box "
        "seam.",
        "- **TU-local helpers** in anonymous namespaces (e.g. "
        "`Render.cpp::format_powers`, `Input.cpp::trim`) are not directly "
        "linkable from outside their TU. To unit-test them they would need "
        "to be hoisted to a header or exposed via a `*_internal.h`. "
        "Otherwise their coverage is achieved indirectly through the public "
        "entry points (`render::render_combat`, `input::read_action`, etc.).",
        "- **`main()` and `parse_args`** are testable only via process-level "
        "tests (spawn `sts2_fight.exe` with argv). They drive 100 % "
        "end-to-end coverage of `Combat::start` and the prompt loop.",
        "- **No exceptions** are thrown by `src/`. `assert` (in `Combat.cpp`) "
        "fires only on internal contract violations and is not part of "
        "user-visible behaviour to test.",
        "",
    ]


def main() -> int:
    data = json.loads(JSON_IN.read_text(encoding="utf-8"))
    types = data["types"]
    namespaces = data["namespaces"]
    funcs = data["functions"]

    parts: list[str] = []
    parts += render_header()
    parts += render_summary(types, namespaces, funcs)
    parts += render_types(types, funcs)
    parts += render_namespaces(namespaces, funcs)
    parts += render_unattached_funcs(funcs)
    parts += render_function_detail(funcs)
    parts += render_testability_notes()

    DOC_OUT.parent.mkdir(parents=True, exist_ok=True)
    DOC_OUT.write_text("\n".join(parts) + "\n", encoding="utf-8")
    print(f"Wrote {DOC_OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
