// Tests for src/game/enemies.{h,cc}.
// Spec: docs/test-plan/02-test-specifications.md §9 (T-ENM-005..060).
//
// HP-roll tests use seeds pinned in tests/seeds/expected_values.h: the
// concrete 38..41 / 51..53 outcomes depend on the host STL's
// uniform_int_distribution implementation, so values are not portable
// across toolchains — they are regenerated by tools/seed-pinner. The
// fixed kCombatTestSeed is used wherever a Combat is constructed, in
// line with the broader test suite convention.

#include <gtest/gtest.h>

#include <vector>

#include "sts2/game/combat.h"
#include "sts2/game/enemies.h"
#include "sts2/game/enemy.h"
#include "sts2/game/rng.h"
#include "sts2/game/types.h"
#include "sts2/game/vitals.h"
#include "tests/game/test_helpers.h"
#include "tests/seeds/expected_values.h"

namespace {

using sts2::tests::helpers::ExpectPowersEq;
using sts2::tests::helpers::MakePower;

using Combat = sts2::game::Combat;
using Enemy = sts2::game::Enemy;
using MoveId = sts2::game::MoveId;
using PowerKind = sts2::game::PowerKind;
using Rng = sts2::game::Rng;

using sts2::tests::seeds::kCalcifiedHp_seed42;
using sts2::tests::seeds::kCalcifiedSeed_hp38;
using sts2::tests::seeds::kCalcifiedSeed_hp39;
using sts2::tests::seeds::kCalcifiedSeed_hp40;
using sts2::tests::seeds::kCalcifiedSeed_hp41;
using sts2::tests::seeds::kCombatTestSeed;
using sts2::tests::seeds::kCultistTestSeed;
using sts2::tests::seeds::kDampHp_seed42;
using sts2::tests::seeds::kDampSeed_hp51;
using sts2::tests::seeds::kDampSeed_hp52;
using sts2::tests::seeds::kDampSeed_hp53;

// -------------------------------------------------------------------------
// 9.1  enemies::make_calcified_cultist(Rng&)
// -------------------------------------------------------------------------

// T-ENM-005 — BP, BV — Stable cultist with kCultistTestSeed. Pins all
// constructor invariants plus the def-use chain hp → max_hp/hp.
TEST(EnemiesMakeCalcified, T_ENM_005_StableCultistAtSeed42) {
  Rng r{kCultistTestSeed};
  Enemy e = sts2::enemies::make_calcified_cultist(r);

  EXPECT_EQ(e.name, "Calcified Cultist");
  EXPECT_EQ(e.vitals.max_hp, e.vitals.hp);
  EXPECT_EQ(e.vitals.hp, kCalcifiedHp_seed42);
  EXPECT_GE(e.vitals.hp, 38);
  EXPECT_LE(e.vitals.hp, 41);
  EXPECT_EQ(e.dark_strike_base, 9);
  EXPECT_EQ(e.ritual_amount, 2);
  EXPECT_EQ(e.current_move, MoveId::kIncantation);
  EXPECT_FALSE(e.performed_first_move);
  EXPECT_EQ(e.vitals.block, 0);
  EXPECT_TRUE(e.vitals.powers.empty());
}

// T-ENM-010 — EG, BV — All four HP outcomes 38..41 reachable; locks the
// closed-interval contract on uniform_int and that the constructor does
// not clamp.
TEST(EnemiesMakeCalcified, T_ENM_010_AllHpOutcomesReachable) {
  {
    Rng r{kCalcifiedSeed_hp38};
    Enemy e = sts2::enemies::make_calcified_cultist(r);
    EXPECT_EQ(e.vitals.hp, 38);
  }
  {
    Rng r{kCalcifiedSeed_hp39};
    Enemy e = sts2::enemies::make_calcified_cultist(r);
    EXPECT_EQ(e.vitals.hp, 39);
  }
  {
    Rng r{kCalcifiedSeed_hp40};
    Enemy e = sts2::enemies::make_calcified_cultist(r);
    EXPECT_EQ(e.vitals.hp, 40);
  }
  {
    Rng r{kCalcifiedSeed_hp41};
    Enemy e = sts2::enemies::make_calcified_cultist(r);
    EXPECT_EQ(e.vitals.hp, 41);
  }
}

// -------------------------------------------------------------------------
// 9.2  enemies::make_damp_cultist(Rng&)
// -------------------------------------------------------------------------

// T-ENM-015 — BP, BV — Mirror of T-ENM-005 for Damp.
TEST(EnemiesMakeDamp, T_ENM_015_StableCultistAtSeed42) {
  Rng r{kCultistTestSeed};
  Enemy e = sts2::enemies::make_damp_cultist(r);

  EXPECT_EQ(e.name, "Damp Cultist");
  EXPECT_EQ(e.vitals.max_hp, e.vitals.hp);
  EXPECT_EQ(e.vitals.hp, kDampHp_seed42);
  EXPECT_GE(e.vitals.hp, 51);
  EXPECT_LE(e.vitals.hp, 53);
  EXPECT_EQ(e.dark_strike_base, 1);
  EXPECT_EQ(e.ritual_amount, 5);
  EXPECT_EQ(e.current_move, MoveId::kIncantation);
  EXPECT_FALSE(e.performed_first_move);
  EXPECT_EQ(e.vitals.block, 0);
  EXPECT_TRUE(e.vitals.powers.empty());
}

// T-ENM-020 — EG, BV — Three HP outcomes 51..53 reachable.
TEST(EnemiesMakeDamp, T_ENM_020_AllHpOutcomesReachable) {
  {
    Rng r{kDampSeed_hp51};
    Enemy e = sts2::enemies::make_damp_cultist(r);
    EXPECT_EQ(e.vitals.hp, 51);
  }
  {
    Rng r{kDampSeed_hp52};
    Enemy e = sts2::enemies::make_damp_cultist(r);
    EXPECT_EQ(e.vitals.hp, 52);
  }
  {
    Rng r{kDampSeed_hp53};
    Enemy e = sts2::enemies::make_damp_cultist(r);
    EXPECT_EQ(e.vitals.hp, 53);
  }
}

// -------------------------------------------------------------------------
// 9.3  enemies::roll_next_move(Enemy&)
// -------------------------------------------------------------------------

// T-ENM-025 — BP, EP — First call latches performed_first_move and leaves
// current_move untouched (D1 TRUE → P1).
TEST(EnemiesRollNextMove, T_ENM_025_FirstCallLatches) {
  Enemy e{};
  e.current_move = MoveId::kIncantation;
  e.performed_first_move = false;

  sts2::enemies::roll_next_move(e);

  EXPECT_TRUE(e.performed_first_move);
  EXPECT_EQ(e.current_move, MoveId::kIncantation);
}

// T-ENM-030 — BP, EP — Incantation → DarkStrike (D1 FALSE; D2 TRUE → P2).
TEST(EnemiesRollNextMove, T_ENM_030_IncantationToDarkStrike) {
  Enemy e{};
  e.current_move = MoveId::kIncantation;
  e.performed_first_move = true;

  sts2::enemies::roll_next_move(e);

  EXPECT_EQ(e.current_move, MoveId::kDarkStrike);
}

// T-ENM-035 — BP — DarkStrike stays (D1 FALSE; D2 FALSE → P3).
TEST(EnemiesRollNextMove, T_ENM_035_DarkStrikeStays) {
  Enemy e{};
  e.current_move = MoveId::kDarkStrike;
  e.performed_first_move = true;

  sts2::enemies::roll_next_move(e);

  EXPECT_EQ(e.current_move, MoveId::kDarkStrike);
}

// T-ENM-040 — DF — Sequence over 4 calls from a fresh enemy:
// [Incantation, DarkStrike, DarkStrike, DarkStrike]. Exercises P1 → P2 → P3 →
// P3.
TEST(EnemiesRollNextMove, T_ENM_040_SequenceOverFourCalls) {
  Enemy e{};
  // Defaults: current_move = Incantation, performed_first_move = false.
  ASSERT_EQ(e.current_move, MoveId::kIncantation);
  ASSERT_FALSE(e.performed_first_move);

  std::vector<MoveId> seq;
  for (int i = 0; i < 4; ++i) {
    sts2::enemies::roll_next_move(e);
    seq.push_back(e.current_move);
  }

  const std::vector<MoveId> expected = {
      MoveId::kIncantation,
      MoveId::kDarkStrike,
      MoveId::kDarkStrike,
      MoveId::kDarkStrike,
  };
  ASSERT_EQ(seq.size(), expected.size());
  for (std::size_t i = 0; i < expected.size(); ++i) {
    EXPECT_EQ(seq[i], expected[i]) << "mismatch at step " << i;
  }
}

// -------------------------------------------------------------------------
// 9.4  enemies::act(Enemy&, Combat&)
// -------------------------------------------------------------------------

// T-ENM-045 — BP, EP — Incantation case applies Ritual (amount = ritual_amount,
// just_applied = true) to the enemy itself via apply_power_to_enemy_self.
TEST(EnemiesAct, T_ENM_045_IncantationAppliesRitualToSelf) {
  Combat c{kCombatTestSeed};
  Enemy e{};
  e.ritual_amount = 2;
  e.current_move = MoveId::kIncantation;

  sts2::enemies::act(e, c);

  ExpectPowersEq(e.vitals.powers, {MakePower(PowerKind::kRitual, 2, true)});
}

// T-ENM-050 — BP, EP — DarkStrike case attacks the player with raw base.
// Player default Vitals is {70, 70, 0, {}}; enemy has no powers.
TEST(EnemiesAct, T_ENM_050_DarkStrikeAttacksPlayer) {
  Combat c{kCombatTestSeed};
  Enemy e{};
  e.dark_strike_base = 9;
  e.current_move = MoveId::kDarkStrike;

  sts2::enemies::act(e, c);

  EXPECT_EQ(c.player().vitals.hp, 61);
}

// T-ENM-055 — DF — DarkStrike with Strength on enemy adds before block check;
// 9 base + 2 Strength = 11 raw damage. Locks integration with
// damage::compute_outgoing on the enemy-source path.
TEST(EnemiesAct, T_ENM_055_DarkStrikeWithStrengthAdds) {
  Combat c{kCombatTestSeed};
  Enemy e{};
  e.dark_strike_base = 9;
  e.current_move = MoveId::kDarkStrike;
  e.vitals.powers = {MakePower(PowerKind::kStrength, 2)};

  sts2::enemies::act(e, c);

  EXPECT_EQ(c.player().vitals.hp, 70 - 11);  // 59
}

// T-ENM-060 — DF — DarkStrike with Weak on enemy applies 0.75 multiplier
// truncated to int: int(9 * 0.75) = int(6.75) = 6.
TEST(EnemiesAct, T_ENM_060_DarkStrikeWithWeakHalves) {
  Combat c{kCombatTestSeed};
  Enemy e{};
  e.dark_strike_base = 9;
  e.current_move = MoveId::kDarkStrike;
  e.vitals.powers = {MakePower(PowerKind::kWeak, 1)};

  sts2::enemies::act(e, c);

  EXPECT_EQ(c.player().vitals.hp, 70 - 6);  // 64
}

}  // namespace
