#pragma once

// AUTO-GENERATED by tools/seed-pinner/pin_seeds.cc. DO NOT EDIT BY HAND.
//
// Toolchain: clang-cl 18.1.8 targeting MSVC STL (Visual Studio 2022).
// Values are NOT portable across STL implementations. libstdc++,
// libc++, and MSVC STL each implement std::uniform_int_distribution
// differently, so the same Rng seed will produce different sequences.
//
// To regenerate after a toolchain change:
//   cmake --build --preset ninja-debug
//   build\ninja-debug\Debug\sts2_seed_pinner.exe > tests\seeds\expected_values.h

#include <array>
#include <cstdint>

#include "sts2/game/types.h"

namespace sts2::tests::seeds {

inline constexpr std::uint64_t kRngTestSeed     = 0xdeadbeefcafeULL;
inline constexpr std::uint64_t kCombatTestSeed  = 0xc0ffeeULL;
inline constexpr std::uint64_t kCultistTestSeed = 0x42ULL;

// T-RNG-005: 10 successive uniform_int(0, 9) calls on Rng{kRngTestSeed}.
inline constexpr std::array<int, 10> kRngSeq_0_9 = {7, 3, 9, 2, 0, 8, 4, 7, 7, 9};

// T-RNG-055: shuffle({1, 2}) on Rng{kRngTestSeed}.
inline constexpr std::array<int, 2>  kShuffle_2  = {1, 2};

// T-RNG-060: shuffle({0..9}) on Rng{kRngTestSeed}.
inline constexpr std::array<int, 10> kShuffle_10 = {5, 8, 2, 6, 4, 0, 1, 9, 3, 7};

// T-ENM-005 / T-ENM-015: cultist HPs from make_*_cultist(Rng{kCultistTestSeed}).
inline constexpr int kCalcifiedHp_seed42 = 39;
inline constexpr int kDampHp_seed42      = 52;

// T-ENM-010 / T-ENM-020: first seed in [0, 2^20) producing a given HP.
inline constexpr std::uint64_t kCalcifiedSeed_hp38 = 0x0ULL;
inline constexpr std::uint64_t kCalcifiedSeed_hp39 = 0x8ULL;
inline constexpr std::uint64_t kCalcifiedSeed_hp40 = 0x3ULL;
inline constexpr std::uint64_t kCalcifiedSeed_hp41 = 0x2ULL;
inline constexpr std::uint64_t kDampSeed_hp51 = 0x0ULL;
inline constexpr std::uint64_t kDampSeed_hp52 = 0x3ULL;
inline constexpr std::uint64_t kDampSeed_hp53 = 0x2ULL;

// Combat tests: order of make_silent_starter_deck() after Rng{kCombatTestSeed}.shuffle(deck).
inline constexpr std::array<CardId, 12> kSilentDeckShuffled_C0FFEE = {
    CardId::Strike,
    CardId::Strike,
    CardId::Neutralize,
    CardId::Survivor,
    CardId::Defend,
    CardId::Defend,
    CardId::Strike,
    CardId::Strike,
    CardId::Defend,
    CardId::Strike,
    CardId::Defend,
    CardId::Defend
};

// Determinism reference: two consecutive uniform_int(0, INT_MAX) on Rng{kRngTestSeed}.
inline constexpr int kRngFirstUniform_0_INTMAX  = 1541086063;
inline constexpr int kRngSecondUniform_0_INTMAX = 765893422;

}  // namespace sts2::tests::seeds
